site_name: Illusionist
site_url: https://github.com/danielfrg/illusionist
copyright: Copyright 2019 - 2020 Daniel Rodriguez

nav:
- Home: index.md

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  favicon: '/assets/img/favicon.ico'
  logo: /assets/img/icon.png

extra_css:
  - assets/css/custom.css

repo_name: 'danielfrg/illusionist'
repo_url: 'https://github.com/danielfrg/illusionist'

plugins:
  - search

markdown_extensions:
  - meta
  - admonition
  - codehilite
  - toc:
      permalink: true

google_analytics:
  - 'UA-35523657-6'
  - 'auto'
