site_name: Illusionist
site_url: https://illusionist.danielfrg.com
site_description: >-
  Illusionist: Interactive Jupyter Notebook without a kernel
copyright: Copyright 2019 - 2023 Daniel Rodriguez
repo_name: danielfrg/illusionist
repo_url: https://github.com/danielfrg/illusionist
edit_uri: ""
site_dir: dist

nav:
  - Home: index.md
  - Usage: usage.ipynb
  - FAQ: faq.md

theme:
  name: material
  favicon: assets/img/favicon.png
  logo: assets/img/icon.png
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - assets/css/material-pygments.css
  - assets/css/custom.css

extra_javascript:
  - assets/js/custom.js

plugins:
  - search
  - mkdocs-jupyter:
      execute: true

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

extra:
  analytics:
    provider: google
    property: G-3673QMK9C4
