site_name: Illusionist
site_url: https://illusionist.danielfrg.com
copyright: Copyright 2019 - 2021 Daniel Rodriguez

nav:
  - Home: index.md
  - Usage: usage.ipynb
  - FAQ: faq.md

repo_name: danielfrg/illusionist
repo_url: https://github.com/danielfrg/illusionist
edit_uri: ""

theme:
  name: material
  favicon: /assets/img/favicon.ico
  logo: /assets/img/icon.png

  palette:
    primary: deep orange
    accent: deep orange

  features:
    - navigation.indexes

extra_css:
  - assets/css/material-pygments.css
  - assets/css/custom.css

extra_javascript:
  - assets/js/custom.js

plugins:
  - search
  - mkdocs-jupyter:
      execute: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - attr_list
  - meta
  - pymdownx.tabbed
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true

extra:
  generator: false
  analytics:
    provider: google
    property: UA-35523657-5
