site_name: Illusionist
site_url: https://illusionist.extrapolations.dev
copyright: Copyright 2019 - 2020 Daniel Rodriguez

nav:
  - Home: index.md
  - Usage: usage.ipynb
  - FAQ: faq.md

repo_name: danielfrg/illusionist
repo_url: https://github.com/danielfrg/illusionist
edit_uri: ""

theme:
  name: material
  custom_dir: docs/theme
  favicon: /assets/img/favicon.ico
  logo: /assets/img/icon.png

extra_css:
  - assets/css/custom.css

plugins:
  - search
  - mkdocs-jupyter:
      execute: false

markdown_extensions:
  - meta
  - admonition
  - codehilite
  - toc:
      permalink: true

google_analytics:
  - "UA-35523657-5"
  - "auto"
