[build-system]
requires = ["setuptools>=42", "setuptools_scm[toml]>=3.4", "wheel"]

# [tool.setuptools_scm]
# root = "../"
# write_to = "python/illusionist/_generated_version.py"

[tool.pytest.ini_options]
norecursedirs = ".git,dist,build,env,venv"
addopts = "illusionist/tests --cov=illusionist --cov-report term-missing"

[tool.coverage.report]
omit = ["illusionist/_generated_version.py", "illusionist/tests/*"]

[tool.black]
target-version = ["py37", "py38"]
exclude = '''
(
    asv_bench/env
  | \.egg
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | node_modules
)
'''

[tool.isort]
# https://black.readthedocs.io/en/stable/the_black_code_style.html#how-black-wraps-lines
multi_line_output=3
lines_after_imports = 2
force_grid_wrap = 0
include_trailing_comma = "true"
use_parentheses = "true"
line_length = 88
