name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 5 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python dependencies
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          pip freeze

      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Install JS dependencies
        run: |
          make npm-install

      - name: Build package
        run: |
          make build

      - name: Install package
        run: |
          cd python
          pip install dist/*.tar.gz
          pip freeze

      - name: Run tests
        if: always()
        run: |
          make test
          make report

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          file: python/coverage.xml
          fail_ci_if_error: true
