name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        node-version: ["15"]

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install JS dependencies
        run: |
          make npm-install

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print Python versions
        run: |
          which python
          which pip
          python --version
          pip --version

      - name: Install Python dependencies
        run: |
          cd python
          python -m pip install --upgrade pip
          pip --version
          pip install -U -r requirements-dev.txt
          pip freeze

      - name: Build package
        run: |
          make build

      - name: Install package
        run: |
          cd python
          pip install dist/*.tar.gz
          pip freeze

      - name: Run tests
        run: |
          make test
          make report

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          file: python/coverage.xml
